In [1]:
import pandas as pd
import numpy as np

In [3]:
# Read the Datasets
sales = pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/sales_raw_dataset.csv")
students = pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/students_raw_dataset.csv")

Q1: Reading the student CSV file and display the first seven rows.

In [4]:
students.head(7)

,StudentID,Name,Gender,Department,Age,StudyHours,Attendance,Math,Physics,Programming,Average
0,1001,Rahim,M,CSE,20.0,15.0,92.0,88.0,84,95.0,NaN
1,1002,Karim,M,Math,21.0,10.0,85.0,75.0,70,78.0,NaN
2,1003,Anika,F,CSE,19.0,18.0,98.0,95.0,92,99.0,NaN
3,1004,Sadia,F,EEE,22.0,8.0,75.0,68.0,65,72.0,NaN
4,1005,Nusrat,F,Math,NaN,12.0,88.0,82.0,80,85.0,NaN
5,1006,Jamal,M,BBA,23.0,6.0,70.0,60.0,58,62.0,NaN
6,1007,Rafi,M,CSE,21.0,20.0,95.0,91.0,89,98.0,NaN

Q2: Displaying number of rows and columns in both datasets.

In [5]:
print("Student Dataset Shape:", students.shape)
print("Sales Dataset Shape:", sales.shape)

Student Dataset Shape: (20, 11)
Sales Dataset Shape: (15, 7)

Q3: Listing all student rows with missing values.

In [6]:
students[students.isnull().any(axis=1)]

,StudentID,Name,Gender,Department,Age,StudyHours,Attendance,Math,Physics,Programming,Average
0,1001,Rahim,M,CSE,20.0,15.0,92.0,88.0,84,95.0,NaN
1,1002,Karim,M,Math,21.0,10.0,85.0,75.0,70,78.0,NaN
2,1003,Anika,F,CSE,19.0,18.0,98.0,95.0,92,99.0,NaN
3,1004,Sadia,F,EEE,22.0,8.0,75.0,68.0,65,72.0,NaN
4,1005,Nusrat,F,Math,NaN,12.0,88.0,82.0,80,85.0,NaN
5,1006,Jamal,M,BBA,23.0,6.0,70.0,60.0,58,62.0,NaN
6,1007,Rafi,M,CSE,21.0,20.0,95.0,91.0,89,98.0,NaN
7,1008,Tania,F,Math,-1.0,14.0,90.0,86.0,82,90.0,NaN
8,1009,Mim,X,EEE,22.0,NaN,72.0,70.0,68,74.0,NaN
9,1010,Rasel,M,BBA,150.0,7.0,68.0,65.0,61,69.0,NaN
10,1011,Nabila,F,CSE,19.0,16.0,96.0,93.0,90,97.0,NaN
11,1012,Arif,M,Math,21.0,11.0,NaN,78.0,76,81.0,NaN
12,1013,Sohan,M,EEE,23.0,13.0,81.0,74.0,72,76.0,NaN
13,1014,Lamia,F,BBA,22.0,8.0,73.0,NaN,66,71.0,NaN
14,1015,Fahim,M,CSE,20.0,19.0,99.0,97.0,95,100.0,NaN
15,1015,Fahim,M,CSE,20.0,19.0,99.0,97.0,95,100.0,NaN
16,1017,NaN,NaN,BIO,18.0,40.0,105.0,110.0,NaN,88.0,NaN
17,1018,NaN,F,Math,NaN,-2.0,-5.0,-10.0,50,NaN,NaN
18,1019,John123,Male,CSE,20.0,12.0,84.0,85.0,73,79.0,NaN
19,1020,Sara,F,NaN,21.0,10.0,91.0,79.0,Absent,82.0,NaN

Q4: Counting missing values in every student column.

In [7]:
students.isnull().sum()

StudentID       0
Name            2
Gender          1
Department      1
Age             2
StudyHours      1
Attendance      1
Math            1
Physics         1
Programming     1
Average        20
dtype: int64

Q5: Finding duplicated Student IDs.

In [8]:
students[students.duplicated(subset="StudentID", keep=False)]

,StudentID,Name,Gender,Department,Age,StudyHours,Attendance,Math,Physics,Programming,Average
14,1015,Fahim,M,CSE,20.0,19.0,99.0,97.0,95,100.0,NaN
15,1015,Fahim,M,CSE,20.0,19.0,99.0,97.0,95,100.0,NaN

Q6: Students with ages outside 16 to 100.

In [9]:
students[(students["Age"] < 16) | (students["Age"] > 100)]

,StudentID,Name,Gender,Department,Age,StudyHours,Attendance,Math,Physics,Programming,Average
7,1008,Tania,F,Math,-1.0,14.0,90.0,86.0,82,90.0,NaN
9,1010,Rasel,M,BBA,150.0,7.0,68.0,65.0,61,69.0,NaN

Q7: Invalid attendance values.

In [10]:
students[
    (students["Attendance"] < 0) |
    (students["Attendance"] > 100)
]

,StudentID,Name,Gender,Department,Age,StudyHours,Attendance,Math,Physics,Programming,Average
16,1017,NaN,NaN,BIO,18.0,40.0,105.0,110.0,NaN,88.0,NaN
17,1018,NaN,F,Math,NaN,-2.0,-5.0,-10.0,50,NaN,NaN

Q8: Converting Physics column to numeric

In [11]:
students["Physics"] = pd.to_numeric(
    students["Physics"],
    errors="coerce"
)
students["Physics"]

0     84.0
1     70.0
2     92.0
3     65.0
4     80.0
5     58.0
6     89.0
7     82.0
8     68.0
9     61.0
10    90.0
11    76.0
12    72.0
13    66.0
14    95.0
15    95.0
16     NaN
17    50.0
18    73.0
19     NaN
Name: Physics, dtype: float64

Q9: Replacing missing ages using median.

In [12]:
valid_age = students["Age"].between(16,100)

median_age = students.loc[
    valid_age,
    "Age"
].median()

students.loc[
    students["Age"].isna(),
    "Age"
] = median_age

students["Age"]

0      20.0
1      21.0
2      19.0
3      22.0
4      21.0
5      23.0
6      21.0
7      -1.0
8      22.0
9     150.0
10     19.0
11     21.0
12     23.0
13     22.0
14     20.0
15     20.0
16     18.0
17     21.0
18     20.0
19     21.0
Name: Age, dtype: float64

Q10:Standardizing Gender.

In [13]:
 students["Gender"] = (
    students["Gender"]
    .astype(str)
    .str.strip()
    .str.upper()
)

gender_map = {
    "M":"M",
    "MALE":"M",
    "F":"F",
    "FEMALE":"F"
}

students["Gender"] = (
    students["Gender"]
    .map(gender_map)
    .fillna("Unknown")
)

students["Gender"].unique()

array(['M', 'F', 'Unknown'], dtype=object)

Q11: Remove duplicate Student IDs.

In [14]:
students = students.drop_duplicates(
    subset="StudentID",
    keep="first"
)

students.shape

(19, 11)

Q12: Calculating average mark.

In [15]:
subjects = [
    "Math",
    "Physics",
    "Programming"
]

students["Average"] = students[
    subjects
].mean(axis=1)

students[["StudentID","Average"]]

    StudentID    Average
0        1001  89.000000
1        1002  74.333333
2        1003  95.333333
3        1004  68.333333
4        1005  82.333333
5        1006  60.000000
6        1007  92.666667
7        1008  86.000000
8        1009  70.666667
9        1010  65.000000
10       1011  93.333333
11       1012  78.333333
12       1013  74.000000
13       1014  68.500000
14       1015  97.333333
16       1017  99.000000
17       1018  20.000000
18       1019  79.000000
19       1020  80.500000

Q13: Assigning Pass or Fail.

In [16]:
students["Result"] = np.where(
    students["Average"] >= 40,
    "Pass",
    "Fail"
)
students[["StudentID","Average","Result"]]

    StudentID    Average Result
0        1001  89.000000   Pass
1        1002  74.333333   Pass
2        1003  95.333333   Pass
3        1004  68.333333   Pass
4        1005  82.333333   Pass
5        1006  60.000000   Pass
6        1007  92.666667   Pass
7        1008  86.000000   Pass
8        1009  70.666667   Pass
9        1010  65.000000   Pass
10       1011  93.333333   Pass
11       1012  78.333333   Pass
12       1013  74.000000   Pass
13       1014  68.500000   Pass
14       1015  97.333333   Pass
16       1017  99.000000   Pass
17       1018  20.000000   Fail
18       1019  79.000000   Pass
19       1020  80.500000   Pass

Q14: Grade Assignment

In [17]:
def grade(avg):

    if avg >= 80:
        return "A"

    elif avg >= 70:
        return "B"

    elif avg >= 60:
        return "C"

    elif avg >= 50:
        return "D"

    else:
        return "F"

students["Grade"] = students["Average"].apply(grade)

students[["StudentID","Average","Grade"]]

    StudentID    Average Grade
0        1001  89.000000     A
1        1002  74.333333     B
2        1003  95.333333     A
3        1004  68.333333     C
4        1005  82.333333     A
5        1006  60.000000     C
6        1007  92.666667     A
7        1008  86.000000     A
8        1009  70.666667     B
9        1010  65.000000     C
10       1011  93.333333     A
11       1012  78.333333     B
12       1013  74.000000     B
13       1014  68.500000     C
14       1015  97.333333     A
16       1017  99.000000     A
17       1018  20.000000     F
18       1019  79.000000     B
19       1020  80.500000     A

Q15: Identifying duplicate Order IDs.

In [18]:
sales[
    sales.duplicated(
        subset="OrderID",
        keep=False
    )
]

    OrderID Month Region   Product  Quantity  UnitPrice  TotalSales
12     2013   Foo   West  Keyboard       7.0       26.0         NaN
13     2013   Jul  South    Laptop       4.0        NaN         NaN

Q16: Finding Invalid Month values.

In [19]:
valid_months = [
    "Jan","Feb","Mar","Apr",
    "May","Jun","Jul","Aug",
    "Sep","Oct","Nov","Dec"
]

sales[
    ~sales["Month"].isin(valid_months)
]

    OrderID Month Region   Product  Quantity  UnitPrice  TotalSales
12     2013   Foo   West  Keyboard       7.0       26.0         NaN
14     2015   NaN   East       NaN      15.0       15.0         NaN

Q17: Replacing nonpositive Quantity.

In [20]:
sales["Quantity"] = pd.to_numeric(
    sales["Quantity"],
    errors="coerce"
)

median_qty = sales.loc[
    sales["Quantity"]>0,
    "Quantity"
].median()

sales.loc[
    (sales["Quantity"]<=0) |
    (sales["Quantity"].isna()),
    "Quantity"
] = median_qty

sales["Quantity"]

0      2.0
1     15.0
2     10.0
3      7.0
4      4.0
5     18.0
6      7.0
7      8.0
8      6.0
9      2.0
10    20.0
11     3.0
12     7.0
13     4.0
14    15.0
Name: Quantity, dtype: float64

Q18: Replacing nonpositive or missing Unit Price.

In [21]:
sales["UnitPrice"] = pd.to_numeric(
    sales["UnitPrice"],
    errors="coerce"
)

median_price = sales.loc[
    sales["UnitPrice"]>0,
    "UnitPrice"
].median()

sales.loc[
    (sales["UnitPrice"]<=0) |
    (sales["UnitPrice"].isna()),
    "UnitPrice"
] = median_price

sales["UnitPrice"]

0     700.0
1      15.0
2      25.0
3     710.0
4     180.0
5      15.0
6     705.0
7     180.0
8     185.0
9     720.0
10     16.0
11    190.0
12     26.0
13    180.0
14     15.0
Name: UnitPrice, dtype: float64

Q19: Calculating TotalSales

In [22]:
sales["TotalSales"] = (
    sales["Quantity"] *
    sales["UnitPrice"]
)

sales[["OrderID","TotalSales"]]

    OrderID  TotalSales
0      2001      1400.0
1      2002       225.0
2      2003       250.0
3      2004      4970.0
4      2005       720.0
5      2006       270.0
6      2007      4935.0
7      2008      1440.0
8      2009      1110.0
9      2010      1440.0
10     2011       320.0
11     2012       570.0
12     2013       182.0
13     2013       720.0
14     2015       225.0

Q20: Saving cleaned CSV files.

In [23]:
students.to_csv(
    "students_cleaned_dataset.csv",
    index=False
)

sales.to_csv(
    "sales_cleaned_dataset.csv",
    index=False
)

Q21: Saving raw and cleaned datasets into Excel.

In [26]:
with pd.ExcelWriter(
    "Python_Lab_Cleaned_Datasets.xlsx",
    engine="openpyxl"
) as writer:

    pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/students_raw_dataset.csv").to_excel(
        writer,
        sheet_name="Students_Raw",
        index=False
    )

    students.to_excel(
        writer,
        sheet_name="Students_Clean",
        index=False
    )

    pd.read_csv("/content/drive/MyDrive/AMDS Practice Datasets/sales_raw_dataset.csv").to_excel(
        writer,
        sheet_name="Sales_Raw",
        index=False
    )

    sales.to_excel(
        writer,
        sheet_name="Sales_Clean",
        index=False
    )

Q22: Verifying duplicate IDs.

In [27]:
print(
    students["StudentID"].duplicated().sum()
)

print(
    sales["OrderID"].duplicated().sum()
)

0
1

Q23: Verifying no missing numerical values.

In [28]:
print(
    students.select_dtypes(
        include=np.number
    ).isnull().sum()
)

print(
    sales.select_dtypes(
        include=np.number
    ).isnull().sum()
)

StudentID      0
Age            0
StudyHours     1
Attendance     1
Math           1
Physics        2
Programming    1
Average        0
dtype: int64
OrderID       0
Quantity      0
UnitPrice     0
TotalSales    0
dtype: int64

Q24: Finding Average student mark by department.

In [29]:
students.groupby(
    "Department"
)["Average"].mean().sort_values(
    ascending=False
)

Department
BIO     99.000000
CSE     91.111111
EEE     71.000000
Math    68.200000
BBA     64.500000
Name: Average, dtype: float64

Q25: Finding Total sales by Product and Region.

In [30]:
print("Sales by Product")

print(
    sales.groupby(
        "Product"
    )["TotalSales"].sum()
)

print()

print("Sales by Region")

print(
    sales.groupby(
        "Region"
    )["TotalSales"].sum()
)

Sales by Product
Product
Keyboard     1872.0
Laptop      13465.0
Monitor      2400.0
Mouse         815.0
Name: TotalSales, dtype: float64

Sales by Region
Region
East     10450.0
North     3660.0
South     2655.0
West      2012.0
Name: TotalSales, dtype: float64